"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var uname = "Hasnain";
var id = "Bc140402269";
var num = 13;
var msg = "Hello";
console.log(uname);
console.log(id);
console.log(num);
console.log(msg);
